export const descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Oak',
    'Modern',
    'Grizzly',
    'Ocean',
    'Zenith',
    'Sea',
    'Sky',
    'Royal',
    'Dusty',
    'Diamond',
    'Urban',
    'Agatha',
    'Celestine',
    'St. Peter Nolasco',
    'St. Ulrich',
    'St. Bonaventure',
    'St. Martin',
    'St. Paul',
    'St. Silverius',
    'St. Angela',
    'St. Nicholas',
    'St. Zacharias',
    'St. Juan',
    'St. Anthony',
    'St. Elizabeth',
    'St. Victor',
    'St. Valentine',
    'St. Dominic',
    'St. Raymond',
    'St. Ignatius',
    'St. Teresa',
    'St. Francis',
    'St. Maurice',
    'St. Catherine'
]

export const places = [
    'Mansion',
    'House barn',
    'Cottage',
    'Duplex',
    'Triplex',
    'Quadruplex',
    'Residential',
    'Apartment',
    'Condominium',
    'Dormitory',
    'Retirement home',
    'Palace',
    'Bishop\'s Palace',
    'Presidential Palace',
    'Office building',
    'Shopping Center',
    'Strip Center',
    'Retail Outlet',
    'Hotel',
    'Motel',
    'Hotel Boutique',
    'Casino',
    'Resort',
    'Bar',
    'Funeral Home',
    'Data Center',
    'Laboratory',
    'Distribution',
    'Farmhouse',
    'Workshop',
    'Barn',
    'Hospital',
    'Sanatorium',
    'Mental Hospital',
    'Nursing Home',
    'College',
    'Elementary School',
    'Secondary School',
    'Orphanage',
    'University',
    'Stadium',
    'Library',
    'Museum',
    'Community Hall',
    'Observatory',
    'Church',
    'Cathedral',
    'Oratory',
    'Chapel',
    'Basilica',
    'Monastery',
    'Synagogue',
    'Temple',
    'Pagoda',
    'Mosque',
    'City Hall',
    'Consulate',
    'Courthouse',
    'Embassy',
    'Fire Station',
    'Post Office',
    'Police Station',
    'Bus Station',
    'Metro Station',
    'Airport',
    'Gym',
    'Studio',
    'Station',
    'Barracks'
]
